-- soft
insert into soft (sname, ver, quant) values ('Overhold', '5.47', 49);
insert into soft (sname, ver, quant) values ('Prodder', '5.5.7', 80);
insert into soft (sname, ver, quant) values ('Fix San', '2.81', 48);
insert into soft (sname, ver, quant) values ('Fintone', '0.67', 56);
insert into soft (sname, ver, quant) values ('Mat Lam Tam', '0.1.3', 42);
insert into soft (sname, ver, quant) values ('Keylex', '0.4.0', 61);
insert into soft (sname, ver, quant) values ('Span', '9.80', 57);
insert into soft (sname, ver, quant) values ('Temp', '0.3.0', 94);
insert into soft (sname, ver, quant) values ('Bitwolf', '0.60', 48);
insert into soft (sname, ver, quant) values ('Zoolab', '0.6.8', 15);

-- pcs
insert into pcs (id, room_id, ip_addr, mac_addr) values (30, 7, '27.204.134.47', '65-F4-33-E5-1B-32');
insert into pcs (id, room_id, ip_addr, mac_addr) values (10, 14, '244.45.143.68', '42-09-E9-28-37-4D');
insert into pcs (id, room_id, ip_addr, mac_addr) values (25, 8, '202.226.207.183', 'F6-19-63-A6-D8-F3');
insert into pcs (id, room_id, ip_addr, mac_addr) values (15, 7, '139.107.162.61', 'AE-EC-4A-5B-54-41');
insert into pcs (id, room_id, ip_addr, mac_addr) values (23, 18, '74.251.196.241', '75-BA-DC-A1-D0-D4');
insert into pcs (id, room_id, ip_addr, mac_addr) values (10, 7, '126.17.180.89', '29-B9-74-CA-8E-84');
insert into pcs (id, room_id, ip_addr, mac_addr) values (8, 14, '175.204.21.199', 'AA-89-4E-8F-F7-5F');
insert into pcs (id, room_id, ip_addr, mac_addr) values (30, 8, '138.49.42.57', '6C-12-E8-F5-C5-91');
insert into pcs (id, room_id, ip_addr, mac_addr) values (4, 4, '149.203.210.198', '23-5F-98-4F-5B-71');
insert into pcs (id, room_id, ip_addr, mac_addr) values (25, 18, '125.73.99.232', 'B6-6E-06-B8-42-47');
insert into pcs (id, room_id, ip_addr, mac_addr) values (8, 19, '135.123.103.48', 'B6-25-F3-73-44-3F');
insert into pcs (id, room_id, ip_addr, mac_addr) values (30, 1, '252.34.82.5', '7D-D1-7C-71-21-E3');
insert into pcs (id, room_id, ip_addr, mac_addr) values (17, 17, '18.203.143.116', '53-19-58-C8-E6-D1');
insert into pcs (id, room_id, ip_addr, mac_addr) values (6, 13, '140.182.29.177', '3D-C0-3E-30-BF-9F');
insert into pcs (id, room_id, ip_addr, mac_addr) values (15, 3, '251.119.180.75', 'E9-9C-47-95-32-69');
insert into pcs (id, room_id, ip_addr, mac_addr) values (1, 19, '78.24.194.17', '1A-A0-DC-25-E0-C6');
insert into pcs (id, room_id, ip_addr, mac_addr) values (18, 11, '170.139.182.189', 'DA-AD-6A-D5-B0-E5');
insert into pcs (id, room_id, ip_addr, mac_addr) values (24, 12, '95.168.198.146', '77-E9-CC-1A-63-E6');
insert into pcs (id, room_id, ip_addr, mac_addr) values (27, 14, '232.111.119.144', 'C6-F7-4E-FE-54-D2');
insert into pcs (id, room_id, ip_addr, mac_addr) values (11, 13, '114.153.144.5', '29-2F-5F-AF-89-E6');
insert into pcs (id, room_id, ip_addr, mac_addr) values (15, 13, '242.24.110.29', '8F-BA-D5-FC-21-E1');
insert into pcs (id, room_id, ip_addr, mac_addr) values (29, 9, '20.82.164.167', '6F-9A-F2-CE-A5-13');
insert into pcs (id, room_id, ip_addr, mac_addr) values (13, 1, '173.182.73.184', 'DD-CF-E3-75-16-24');
insert into pcs (id, room_id, ip_addr, mac_addr) values (4, 13, '41.66.74.49', '08-6E-B0-D5-6B-60');
insert into pcs (id, room_id, ip_addr, mac_addr) values (6, 18, '165.123.31.14', '30-FF-6A-7D-E2-85');
insert into pcs (id, room_id, ip_addr, mac_addr) values (8, 1, '9.148.92.75', '91-9E-FB-DE-E8-65');
insert into pcs (id, room_id, ip_addr, mac_addr) values (12, 9, '26.176.235.118', '38-03-C5-1B-C5-24');
insert into pcs (id, room_id, ip_addr, mac_addr) values (25, 14, '222.192.29.224', 'C1-B5-4D-68-63-EC');
insert into pcs (id, room_id, ip_addr, mac_addr) values (20, 18, '223.96.111.120', 'CE-07-BB-4D-5F-13');
insert into pcs (id, room_id, ip_addr, mac_addr) values (7, 9, '143.237.29.27', 'CA-69-72-97-F4-0C');

--installs
insert into installs (pc_id, soft_id) values (27, 2);
insert into installs (pc_id, soft_id) values (2, 1);
insert into installs (pc_id, soft_id) values (8, 5);
insert into installs (pc_id, soft_id) values (6, 2);
insert into installs (pc_id, soft_id) values (5, 1);
insert into installs (pc_id, soft_id) values (6, 1);
insert into installs (pc_id, soft_id) values (2, 2);
insert into installs (pc_id, soft_id) values (19, 5);
insert into installs (pc_id, soft_id) values (14, 1);
insert into installs (pc_id, soft_id) values (22, 2);
insert into installs (pc_id, soft_id) values (4, 2);
insert into installs (pc_id, soft_id) values (8, 4);
insert into installs (pc_id, soft_id) values (2, 3);
insert into installs (pc_id, soft_id) values (13, 3);
insert into installs (pc_id, soft_id) values (11, 5);
insert into installs (pc_id, soft_id) values (30, 4);
insert into installs (pc_id, soft_id) values (14, 5);
insert into installs (pc_id, soft_id) values (30, 5);
insert into installs (pc_id, soft_id) values (25, 2);
insert into installs (pc_id, soft_id) values (18, 4);
insert into installs (pc_id, soft_id) values (25, 2);
insert into installs (pc_id, soft_id) values (6, 5);
insert into installs (pc_id, soft_id) values (20, 1);
insert into installs (pc_id, soft_id) values (3, 4);
insert into installs (pc_id, soft_id) values (21, 1);
insert into installs (pc_id, soft_id) values (7, 5);
insert into installs (pc_id, soft_id) values (2, 4);
insert into installs (pc_id, soft_id) values (2, 5);
insert into installs (pc_id, soft_id) values (19, 1);
insert into installs (pc_id, soft_id) values (9, 1);
insert into installs (pc_id, soft_id) values (27, 1);
insert into installs (pc_id, soft_id) values (15, 1);
insert into installs (pc_id, soft_id) values (15, 4);
insert into installs (pc_id, soft_id) values (14, 1);
insert into installs (pc_id, soft_id) values (6, 1);
insert into installs (pc_id, soft_id) values (28, 2);
insert into installs (pc_id, soft_id) values (21, 2);
insert into installs (pc_id, soft_id) values (4, 1);
insert into installs (pc_id, soft_id) values (23, 4);
insert into installs (pc_id, soft_id) values (17, 3);
insert into installs (pc_id, soft_id) values (2, 1);
insert into installs (pc_id, soft_id) values (8, 2);
insert into installs (pc_id, soft_id) values (1, 2);
insert into installs (pc_id, soft_id) values (15, 5);
insert into installs (pc_id, soft_id) values (22, 5);
insert into installs (pc_id, soft_id) values (12, 4);
insert into installs (pc_id, soft_id) values (8, 4);
insert into installs (pc_id, soft_id) values (4, 4);
insert into installs (pc_id, soft_id) values (7, 4);
insert into installs (pc_id, soft_id) values (10, 4);
insert into installs (pc_id, soft_id) values (18, 4);
insert into installs (pc_id, soft_id) values (3, 3);
insert into installs (pc_id, soft_id) values (5, 4);
insert into installs (pc_id, soft_id) values (11, 4);
insert into installs (pc_id, soft_id) values (28, 2);
insert into installs (pc_id, soft_id) values (11, 5);
insert into installs (pc_id, soft_id) values (22, 2);
insert into installs (pc_id, soft_id) values (3, 4);
insert into installs (pc_id, soft_id) values (27, 5);
insert into installs (pc_id, soft_id) values (16, 5);
insert into installs (pc_id, soft_id) values (3, 2);
insert into installs (pc_id, soft_id) values (5, 2);
insert into installs (pc_id, soft_id) values (15, 4);
insert into installs (pc_id, soft_id) values (6, 3);
insert into installs (pc_id, soft_id) values (26, 5);
insert into installs (pc_id, soft_id) values (16, 5);
insert into installs (pc_id, soft_id) values (27, 4);
insert into installs (pc_id, soft_id) values (4, 2);
insert into installs (pc_id, soft_id) values (1, 3);
insert into installs (pc_id, soft_id) values (17, 1);

--rooms
insert into rooms (num, emp_id) values (7, 2);
insert into rooms (num, emp_id) values (9, 2);
insert into rooms (num, emp_id) values (10, 8);
insert into rooms (num, emp_id) values (16, 6);
insert into rooms (num, emp_id) values (5, 10);
insert into rooms (num, emp_id) values (8, 10);
insert into rooms (num, emp_id) values (18, 2);
insert into rooms (num, emp_id) values (3, 4);
insert into rooms (num, emp_id) values (6, 8);
insert into rooms (num, emp_id) values (18, 7);
insert into rooms (num, emp_id) values (16, 4);
insert into rooms (num, emp_id) values (10, 8);
insert into rooms (num, emp_id) values (7, 6);
insert into rooms (num, emp_id) values (2, 9);
insert into rooms (num, emp_id) values (17, 3);
insert into rooms (num, emp_id) values (15, 8);
insert into rooms (num, emp_id) values (19, 3);
insert into rooms (num, emp_id) values (13, 5);
insert into rooms (num, emp_id) values (14, 3);
insert into rooms (num, emp_id) values (12, 5);

--employees
insert into employees (lname, fname, mname) values ('Ceaser', 'Patrick', 1);
insert into employees (lname, fname, mname) values ('Dudney', 'Caryl', 1);
insert into employees (lname, fname, mname) values ('Camellini', 'Gabrielle', 1);
insert into employees (lname, fname, mname) values ('Garbett', 'Koren', 1);
insert into employees (lname, fname, mname) values ('Bellis', 'Nevsa', 1);
insert into employees (lname, fname, mname) values ('Venus', 'Chick', 1);
insert into employees (lname, fname, mname) values ('Jerrand', 'Cathi', 1);
insert into employees (lname, fname, mname) values ('Lothean', 'Ralph', 1);
insert into employees (lname, fname, mname) values ('Stiegar', 'Zarah', 1);
insert into employees (lname, fname, mname) values ('Feaveryear', 'Andie', 1);
insert into employees (lname, fname, mname) values ('Nevins', 'Buck', 1);
insert into employees (lname, fname, mname) values ('McAw', 'Maddy', 1);
insert into employees (lname, fname, mname) values ('MacIlhagga', 'Sky', 1);
insert into employees (lname, fname, mname) values ('Champkins', 'Farra', 1);
insert into employees (lname, fname, mname) values ('Ferriere', 'Celia', 1);
insert into employees (lname, fname, mname) values ('Bernard', 'Layla', 1);
insert into employees (lname, fname, mname) values ('Eagger', 'Erina', 1);
insert into employees (lname, fname, mname) values ('Mathonnet', 'Halimeda', 1);
insert into employees (lname, fname, mname) values ('Tonbye', 'Cicily', 1);
insert into employees (lname, fname, mname) values ('Lalonde', 'Rafaello', 1);

--switches
insert into switches (model_name, quant_ports, serial_number) values ('TP-LINK TL-SG1008D', 11, 1418009);
insert into switches (model_name, quant_ports, serial_number) values ('Dlink S42901', 12, 1646287);
insert into switches (model_name, quant_ports, serial_number) values ('TP-LINK TL-SG1008D', 33, 1500744);
insert into switches (model_name, quant_ports, serial_number) values ('TP-LINK TL-SG1024DE', 39, 2193808);
