INSERT INTO actors(name, role) VALUES('Kenny Rose', 'Jimmy'),
('Ethan Carter', 'Son of President'),
('Derek Rose', 'Derek Rose'),
('Joan Smit', 'Special Agent 008'),
('Naomi Butch', 'Emily'),
('Stella Bogomi', 'F-98'),
('Jack Masaki', 'Sherif'),
('Andrew Johrood', 'Tupac Shakur'),
('Boris Fidger', 'Eminem'),
('Malcolm Alabown', 'Barak Obama'),
('Carl Jigly', 'Tommy'),
('Chad Rose', 'Father'),
('Maksim Altufiev', 'Thief'),
('Eva Rosenberg', 'Mobly'),
('Anthony Braus', 'Mark Sanly'),
('Anderson Grim', 'John Diglan'),
('George Lichy', 'Master 5Gen'),
('Travis Shinly', 'Pilot of MassacroSh-0234'),
('Nikita Potov', 'Elliot Boston'),
('Wayne Eall', 'Maxim Brechev');
